const MOVEMENT_SPEED = 3;
const MOVEMENT_FREQUENCY_RATE = 10;
const MOVEMENT_SPEED_BOOST = 6;
const INITIAL_POSITION = { x: 200, y: 200 };
const BROADCAST_RATE_INTERVAL = 10;
const THROTTLING_INTERVAL = 0;

module.exports = {
  MOVEMENT_SPEED,
  MOVEMENT_SPEED_BOOST,
  INITIAL_POSITION,
  BROADCAST_RATE_INTERVAL,
  MOVEMENT_FREQUENCY_RATE,
  THROTTLING_INTERVAL,
};
