// Canvas
const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 800;

// Game
const GAME_SPEED_RATE = 16.67;

// Websocket connection
const BROADCAST_RATE_INTERVAL = 200;

// Pawn
const RADIUS = 10;
const MOVEMENT_SPEED = 300;

// Bullet
const BULLET_SPEED = 3;
const BULLET_COOLDOWN = 200;

module.exports = {
  RADIUS,
  MOVEMENT_SPEED,
  BROADCAST_RATE_INTERVAL,
  GAME_SPEED_RATE,
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  BULLET_SPEED,
  BULLET_COOLDOWN,
};
